# Structure of the output

class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluatoinArtifact:...
class ModelPusherArtifact:...