# Define the input structure of the entity

class DataIngestionConfig:...
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluatoinConfig:...
class ModelPusherConfig:...